/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

import com.optum.giraffle.tasks.GsqlTask
plugins {
     id("com.optum.giraffle") version "1.3.4.1-SNAPSHOT"
     id("net.saliman.properties") version "1.5.1"
}
repositories{
     jcenter()
}

